# Generated by Django 6.0 on 2026-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_mahsulotlar_bepulyetkazish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Badiiy', 'Badiiy'), ('Biznes', 'Biznes'), ('Darslik', 'Darslik'), ('Tarix', 'Tarix')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahsulotlar',
        ),
    ]
