# Generated by Django 6.0 on 2026-02-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Yozuvchi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='kategoriya',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='nomi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='tavsifi',
        ),
        migrations.AddField(
            model_name='book',
            name='ktob',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
