# Generated by Django 6.0 on 2026-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_author_book_yozuvchi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ktob',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
