# Generated by Django 6.0.2 on 2026-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=50)),
                ('janr', models.CharField(max_length=50)),
                ('davlat', models.CharField(max_length=50)),
                ('yili', models.IntegerField()),
                ('davomiy', models.CharField(max_length=50)),
                ('tavsifi', models.TextField()),
                ('video_img', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='ktob',
            field=models.ImageField(upload_to='book/'),
        ),
    ]
