# Generated by Django 6.0.2 on 2026-02-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_main_movie_alter_book_ktob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Movie',
        ),
    ]
