# Generated by Django 6.0.2 on 2026-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_book_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktob1', models.ImageField(upload_to='book1/')),
                ('nomi1', models.CharField(max_length=200)),
                ('Yozuvchi1', models.CharField(max_length=200)),
                ('tavsifi1', models.TextField(blank=True)),
                ('rating1', models.IntegerField(default=0)),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
